In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.decomposition import PCA

In [9]:
# Inisialisasi DataFrame kosong untuk menyimpan semua data
all_data = pd.DataFrame()

# Loop melalui setiap file
for i in range(0, 10):  # Ini akan loop dari 1 sampai 9
    file_name = f'titik{i}_ruijie.csv'
    # Baca file
    temp_data = pd.read_csv(file_name)
    temp_csi = temp_data['CSI_DATA']
    cleaned_file_path = f'cleaned_file_titik{i}.csv'
    temp_csi.to_csv(cleaned_file_path, index=False)

# Sekarang, all_data berisi data dari semua file

In [2]:
def parse_csi_string(csi_string):
    return [int(x) for x in csi_string.strip('[]').split()]

In [5]:
all_data = pd.DataFrame()

for i in range(0, 10):  # Ini akan loop dari 0 sampai 9
    file_path = f'cleaned_file_titik{i}.csv'
    # Baca file
    data = pd.read_csv(file_path, converters={0: parse_csi_string})
    parsed_data = pd.DataFrame(data.iloc[:, 0].tolist())
    parsed_data['Titik'] = i
    all_data = pd.concat([all_data, parsed_data], ignore_index=True)

In [6]:
all_data

,0,1,2,3,4,5,6,7,8,9,...,119,120,121,122,123,124,125,126,127,Titik
0,-125,48,8,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,74,-96,4,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,-113,-16,8,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,-125,48,8,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,-113,-16,8,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6985,-64,0,12,0,21,23,13,19,19,15,...,23,16,16,26,27,16,21,17,17,9
6986,-64,0,12,0,27,9,31,9,27,4,...,14,22,6,27,8,19,8,23,5,9
6987,-64,0,12,0,-24,17,-23,19,-25,5,...,14,-27,19,-20,15,-29,19,-19,14,9
6988,-64,0,12,0,-2,-27,9,-23,5,-31,...,-22,11,-23,9,-18,2,-27,17,-35,9
6989,-64,0,12,0,-14,25,-31,21,-21,16,...,22,-12,18,-14,22,-15,24,-13,23,9

In [13]:
shuffled_data = all_data.sample(frac=1).reset_index(drop=True)

In [14]:
shuffled_data

,0,1,2,3,4,5,6,7,8,9,...,122,123,124,125,126,127,rssi,sig_len,len,Titik
0,-62,32,12,0,0,0,0,0,0,0,...,0,0,0,0,0,0,-83,194,128,6
1,-30,32,14,0,0,0,0,0,0,0,...,0,0,0,0,0,0,-86,226,128,6
2,-72,-128,11,0,0,0,0,0,0,0,...,0,0,0,0,0,0,-83,184,128,3
3,-30,32,14,0,0,0,0,0,0,0,...,0,0,0,0,0,0,-74,226,128,5
4,-123,80,8,0,0,0,0,0,0,0,...,0,0,0,0,0,0,-77,133,128,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6985,-73,112,11,0,0,0,0,0,0,0,...,0,0,0,0,0,0,-77,183,128,5
6986,123,48,7,0,0,0,0,0,0,0,...,0,0,0,0,0,0,-77,123,128,7
6987,-125,48,8,0,0,0,0,0,0,0,...,0,0,0,0,0,0,-81,131,128,0
6988,-109,48,9,0,0,0,0,0,0,0,...,0,0,0,0,0,0,-69,147,128,6
6989,-126,-96,7,0,0,0,0,0,0,0,...,0,0,0,0,0,0,-83,130,128,7

In [15]:
data = shuffled_data.sample(frac=1).reset_index(drop=True)

In [16]:
data

,0,1,2,3,4,5,6,7,8,9,...,122,123,124,125,126,127,rssi,sig_len,len,Titik
0,-62,32,12,0,0,0,0,0,0,0,...,0,0,0,0,0,0,-82,194,128,6
1,-64,0,12,0,0,0,0,0,0,0,...,0,0,0,0,0,0,-34,192,128,6
2,-62,32,12,0,0,0,0,0,0,0,...,0,0,0,0,0,0,-87,194,128,6
3,-30,32,14,0,0,0,0,0,0,0,...,0,0,0,0,0,0,-78,226,128,4
4,-73,112,11,0,0,0,0,0,0,0,...,0,0,0,0,0,0,-79,183,128,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6985,-114,96,8,0,0,0,0,0,0,0,...,0,0,0,0,0,0,-77,142,128,8
6986,-73,112,11,0,0,0,0,0,0,0,...,0,0,0,0,0,0,-73,183,128,5
6987,-72,-128,11,0,0,0,0,0,0,0,...,0,0,0,0,0,0,-83,184,128,1
6988,30,-32,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,-78,30,128,7
6989,-106,-32,8,0,0,0,0,0,0,0,...,0,0,0,0,0,0,-78,150,128,7

In [19]:
data.to_csv('csi_data_tw2ke2.csv', index=False)